name: Build and Deploy Patient Service

on:
  push:
    branches:
      - main
    paths:
      - 'patient-service/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
          cd patient-service
          docker build -t patient-service .

      - name: Tag and Push to Amazon ECR
        run: |
          ECR_REGISTRY=373649774472.dkr.ecr.ap-south-1.amazonaws.com
          IMAGE_NAME=patient-service
          docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest
          docker push $ECR_REGISTRY/$IMAGE_NAME:latest

      - name: Render ECS Task Definition for Patient Service
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs/patient-task-def.json
          container-name: patient-service
          image: 373649774472.dkr.ecr.ap-south-1.amazonaws.com/patient-service:latest

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: dev-ecs-cluster
          service: patient-service
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          wait-for-service-stability: true

